name = "gleam_javascript"
version = "0.8.0"
licences = ["Apache-2.0"]
description = "Work with JavaScript types and values in Gleam"

gleam = ">= 0.32.0"
target = "javascript"

repository = { type = "github", user = "gleam-lang", repo = "javascript" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = "~> 0.19 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
